### ISSUE TITLE
Enable/disable the plugin per world

### ISSUE THREAD

**Issue by Onyxtite** [ShaneBeeTK/SurvivalPlus#2]
Hey there, first of all good job on updating the plugin,  just tried it and didn't encounter one error :)

Could you add a setting to make the plugin active only on certain worlds?

While the plugin is awesome for a hard world experience, I'm sure there are at least a few players who'd enjoy a more relaxed gameplay, and while I want to support both, it wouldn't be fair for them to compete with eachother on the same world.

ps: A way this could possibly be done would be just by adding a permission node required to be affected by the plugin, and then with a permissions plugin we could just give that permission node to players only on a certain world. Feel free to do it another way if its easier, its just an idea i came up with ;)

Anyhow, glad you revived the plugin, thanks =) !

**Comment by ShaneBeee** [comment]
This would be difficult to do, and mainly for the recipes.

When the server starts up, this plugin removes a bunch of recipes, and adds in the custom ones, and this task cant be done on a per world basis.
That being said, a lot of the things could be disabled in a world, but the players wouldn't have access to the correct recipes. 

I do see your point, and wish it was easier to disable in certain worlds, but unfortunately it wouldn't be a simple task without doing a fairly large re-write to the plugin.

**Comment by Onyxtite** [comment]
Hi, thanks for the quick answer! Yeah, i understand its difficult, but if the recipes are whats holding you from doing it, then don't worry at all !

The recipes already have a  toggle to be disabled, so people who want to use the plugin per world can just disable them.
-> Server owners who actually care for the recipes could then just recreate them on a perworld basis with this free plugin, https://www.spigotmc.org/resources/%E2%99%A6-conditional-crafting-%E2%99%A6-bring-crafting-to-a-new-level-1-13.65094/ 

If you decide to do it, it'd be awsome :) Thanks for considering it!

**Comment by ShaneBeee** [comment]
You're welcome.

I think this plugin would be to hard to implement that. With 1.14 out now, custom items have changed a bit, and Im taking advantage of this new system (CustomModelData tags), that being said, it would be near impossible to use another plugin for the recipes.

The recipes are registered to the server itself, and therefor they show up in your recipe book (in the crafting table) so I think its impossible to implement per world, unless I were to completely re-write the recipe system, using events instead, and honestly I have no desire to do that, as it wouldn't give the proper effect.


I do thank you for your suggestion and the thoroughness you put into it. Not very often I get well detailed suggestions.

**Comment by Onyxtite** [comment]
Alright, I get your point now. Recreating recipes for custom items made by the plugin wouldn't be possible using an external one. I'd still would totally love a perworld toggle  for the food/water/fatigue though, if you'd like i can try making it myself? I'm kinda nooby so it will take me a while, but I can probably pull it off eventually ;)

**Comment by ShaneBeee** [comment]
That actually is a good idea. That system can get a bit annoying sometimes.

Ill look into it, its quite a big system so Im not sure how easy it will be to disable it per world.

**Comment by Onyxtite** [comment]
Awesome thanks!

**Comment by ShaneBeee** [comment]
I'm moving this repo over to BitBucket

I have copied this issue over to there incase you want to follow it.
You can find it [**HERE**](https://bitbucket.org/ShaneBeeStudios/survivalplus/issues/1/enable-disable-the-plugin-per-world)
